# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: glider 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "glider"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David Pelaez"]
  s.date = "2014-10-16"
  s.description = "Glider simplifies the usage of Amazon SWF by adopting convention over configuration and exposing a simplified object oriented API seeking to offer Ruby libraries' traditional simplicity while keeping the benefits of SWF like auditability, timers, timeouts and process decoupling."
  s.email = "david@vlipco.co"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "VERSION",
    "example/Gemfile",
    "example/Gemfile.lock",
    "example/Procfile",
    "example/boot.rb",
    "example/example.rb",
    "example/trigger.rb",
    "glider.gemspec",
    "lib/glider.rb",
    "lib/glider/aws_sdk_patch.rb",
    "lib/glider/component_class_helpers.rb",
    "lib/glider/component_instance.rb",
    "lib/glider/component_polling.rb",
    "lib/glider/glider_globals.rb",
    "readme.md"
  ]
  s.homepage = "http://github.com/vlipco/glider"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Minimal opinionated wrapper around SimpleWorkflow"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, ["< 2.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<spawnling>, ["~> 2.1.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<aws-sdk>, ["< 2.0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<spawnling>, ["~> 2.1.5"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<aws-sdk>, ["< 2.0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<spawnling>, ["~> 2.1.5"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

